/* tslint:disable */
/* eslint-disable */
/**
 * SUT SA Example API Eatinghistory
 * This is a sample server for SUT SE 2563
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ControllersMealplan
 */
export interface ControllersMealplan {
    /**
     * 
     * @type {number}
     * @memberof ControllersMealplan
     */
    foodid?: number;
    /**
     * 
     * @type {string}
     * @memberof ControllersMealplan
     */
    mealdate?: string;
    /**
     * 
     * @type {number}
     * @memberof ControllersMealplan
     */
    mealid?: number;
    /**
     * 
     * @type {number}
     * @memberof ControllersMealplan
     */
    ownerid?: number;
}

export function ControllersMealplanFromJSON(json: any): ControllersMealplan {
    return ControllersMealplanFromJSONTyped(json, false);
}

export function ControllersMealplanFromJSONTyped(json: any, ignoreDiscriminator: boolean): ControllersMealplan {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'foodid': !exists(json, 'foodid') ? undefined : json['foodid'],
        'mealdate': !exists(json, 'mealdate') ? undefined : json['mealdate'],
        'mealid': !exists(json, 'mealid') ? undefined : json['mealid'],
        'ownerid': !exists(json, 'ownerid') ? undefined : json['ownerid'],
    };
}

export function ControllersMealplanToJSON(value?: ControllersMealplan | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'foodid': value.foodid,
        'mealdate': value.mealdate,
        'mealid': value.mealid,
        'ownerid': value.ownerid,
    };
}


