/* tslint:disable */
/* eslint-disable */
/**
 * SUT SA Example API Eatinghistory
 * This is a sample server for SUT SE 2563
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    EntEatinghistory,
    EntEatinghistoryFromJSON,
    EntEatinghistoryFromJSONTyped,
    EntEatinghistoryToJSON,
} from './';

/**
 * 
 * @export
 * @interface EntTasteEdges
 */
export interface EntTasteEdges {
    /**
     * Eatinghistorys holds the value of the eatinghistorys edge.
     * @type {Array<EntEatinghistory>}
     * @memberof EntTasteEdges
     */
    eatinghistorys?: Array<EntEatinghistory>;
}

export function EntTasteEdgesFromJSON(json: any): EntTasteEdges {
    return EntTasteEdgesFromJSONTyped(json, false);
}

export function EntTasteEdgesFromJSONTyped(json: any, ignoreDiscriminator: boolean): EntTasteEdges {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'eatinghistorys': !exists(json, 'eatinghistorys') ? undefined : ((json['eatinghistorys'] as Array<any>).map(EntEatinghistoryFromJSON)),
    };
}

export function EntTasteEdgesToJSON(value?: EntTasteEdges | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'eatinghistorys': value.eatinghistorys === undefined ? undefined : ((value.eatinghistorys as Array<any>).map(EntEatinghistoryToJSON)),
    };
}


