/* tslint:disable */
/* eslint-disable */
/**
 * SUT SA Example API Eatinghistory
 * This is a sample server for SUT SE 2563
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    EntEatinghistory,
    EntEatinghistoryFromJSON,
    EntEatinghistoryFromJSONTyped,
    EntEatinghistoryToJSON,
    EntFoodmenu,
    EntFoodmenuFromJSON,
    EntFoodmenuFromJSONTyped,
    EntFoodmenuToJSON,
    EntMealplan,
    EntMealplanFromJSON,
    EntMealplanFromJSONTyped,
    EntMealplanToJSON,
} from './';

/**
 * 
 * @export
 * @interface EntUserEdges
 */
export interface EntUserEdges {
    /**
     * Eatinghistorys holds the value of the eatinghistorys edge.
     * @type {Array<EntEatinghistory>}
     * @memberof EntUserEdges
     */
    eatinghistorys?: Array<EntEatinghistory>;
    /**
     * Foodmenus holds the value of the foodmenus edge.
     * @type {Array<EntFoodmenu>}
     * @memberof EntUserEdges
     */
    foodmenus?: Array<EntFoodmenu>;
    /**
     * Mealplans holds the value of the mealplans edge.
     * @type {Array<EntMealplan>}
     * @memberof EntUserEdges
     */
    mealplans?: Array<EntMealplan>;
}

export function EntUserEdgesFromJSON(json: any): EntUserEdges {
    return EntUserEdgesFromJSONTyped(json, false);
}

export function EntUserEdgesFromJSONTyped(json: any, ignoreDiscriminator: boolean): EntUserEdges {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'eatinghistorys': !exists(json, 'eatinghistorys') ? undefined : ((json['eatinghistorys'] as Array<any>).map(EntEatinghistoryFromJSON)),
        'foodmenus': !exists(json, 'foodmenus') ? undefined : ((json['foodmenus'] as Array<any>).map(EntFoodmenuFromJSON)),
        'mealplans': !exists(json, 'mealplans') ? undefined : ((json['mealplans'] as Array<any>).map(EntMealplanFromJSON)),
    };
}

export function EntUserEdgesToJSON(value?: EntUserEdges | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'eatinghistorys': value.eatinghistorys === undefined ? undefined : ((value.eatinghistorys as Array<any>).map(EntEatinghistoryToJSON)),
        'foodmenus': value.foodmenus === undefined ? undefined : ((value.foodmenus as Array<any>).map(EntFoodmenuToJSON)),
        'mealplans': value.mealplans === undefined ? undefined : ((value.mealplans as Array<any>).map(EntMealplanToJSON)),
    };
}


