// Code generated by entc, DO NOT EDIT.

package taste

const (
	// Label holds the string label denoting the taste type in the database.
	Label = "taste"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldTaste holds the string denoting the taste field in the database.
	FieldTaste = "taste"

	// EdgeEatinghistorys holds the string denoting the eatinghistorys edge name in mutations.
	EdgeEatinghistorys = "eatinghistorys"

	// Table holds the table name of the taste in the database.
	Table = "tastes"
	// EatinghistorysTable is the table the holds the eatinghistorys relation/edge.
	EatinghistorysTable = "eatinghistories"
	// EatinghistorysInverseTable is the table name for the Eatinghistory entity.
	// It exists in this package in order to avoid circular dependency with the "eatinghistory" package.
	EatinghistorysInverseTable = "eatinghistories"
	// EatinghistorysColumn is the table column denoting the eatinghistorys relation/edge.
	EatinghistorysColumn = "taste_id"
)

// Columns holds all SQL columns for taste fields.
var Columns = []string{
	FieldID,
	FieldTaste,
}

var (
	// TasteValidator is a validator for the "taste" field. It is called by the builders before save.
	TasteValidator func(string) error
)
