// Code generated by entc, DO NOT EDIT.

package taste

import (
	"github.com/Teeth/app/ent/predicate"
	"github.com/facebookincubator/ent/dialect/sql"
	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their identifier.
func ID(id int) predicate.Taste {
	return predicate.Taste(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Taste {
	return predicate.Taste(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Taste {
	return predicate.Taste(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldID), id))
	})
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Taste {
	return predicate.Taste(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(ids) == 0 {
			s.Where(sql.False())
			return
		}
		v := make([]interface{}, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.In(s.C(FieldID), v...))
	})
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Taste {
	return predicate.Taste(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(ids) == 0 {
			s.Where(sql.False())
			return
		}
		v := make([]interface{}, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.NotIn(s.C(FieldID), v...))
	})
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Taste {
	return predicate.Taste(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldID), id))
	})
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Taste {
	return predicate.Taste(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldID), id))
	})
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Taste {
	return predicate.Taste(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldID), id))
	})
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Taste {
	return predicate.Taste(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldID), id))
	})
}

// Taste applies equality check predicate on the "taste" field. It's identical to TasteEQ.
func Taste(v string) predicate.Taste {
	return predicate.Taste(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldTaste), v))
	})
}

// TasteEQ applies the EQ predicate on the "taste" field.
func TasteEQ(v string) predicate.Taste {
	return predicate.Taste(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldTaste), v))
	})
}

// TasteNEQ applies the NEQ predicate on the "taste" field.
func TasteNEQ(v string) predicate.Taste {
	return predicate.Taste(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldTaste), v))
	})
}

// TasteIn applies the In predicate on the "taste" field.
func TasteIn(vs ...string) predicate.Taste {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Taste(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldTaste), v...))
	})
}

// TasteNotIn applies the NotIn predicate on the "taste" field.
func TasteNotIn(vs ...string) predicate.Taste {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Taste(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldTaste), v...))
	})
}

// TasteGT applies the GT predicate on the "taste" field.
func TasteGT(v string) predicate.Taste {
	return predicate.Taste(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldTaste), v))
	})
}

// TasteGTE applies the GTE predicate on the "taste" field.
func TasteGTE(v string) predicate.Taste {
	return predicate.Taste(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldTaste), v))
	})
}

// TasteLT applies the LT predicate on the "taste" field.
func TasteLT(v string) predicate.Taste {
	return predicate.Taste(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldTaste), v))
	})
}

// TasteLTE applies the LTE predicate on the "taste" field.
func TasteLTE(v string) predicate.Taste {
	return predicate.Taste(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldTaste), v))
	})
}

// TasteContains applies the Contains predicate on the "taste" field.
func TasteContains(v string) predicate.Taste {
	return predicate.Taste(func(s *sql.Selector) {
		s.Where(sql.Contains(s.C(FieldTaste), v))
	})
}

// TasteHasPrefix applies the HasPrefix predicate on the "taste" field.
func TasteHasPrefix(v string) predicate.Taste {
	return predicate.Taste(func(s *sql.Selector) {
		s.Where(sql.HasPrefix(s.C(FieldTaste), v))
	})
}

// TasteHasSuffix applies the HasSuffix predicate on the "taste" field.
func TasteHasSuffix(v string) predicate.Taste {
	return predicate.Taste(func(s *sql.Selector) {
		s.Where(sql.HasSuffix(s.C(FieldTaste), v))
	})
}

// TasteEqualFold applies the EqualFold predicate on the "taste" field.
func TasteEqualFold(v string) predicate.Taste {
	return predicate.Taste(func(s *sql.Selector) {
		s.Where(sql.EqualFold(s.C(FieldTaste), v))
	})
}

// TasteContainsFold applies the ContainsFold predicate on the "taste" field.
func TasteContainsFold(v string) predicate.Taste {
	return predicate.Taste(func(s *sql.Selector) {
		s.Where(sql.ContainsFold(s.C(FieldTaste), v))
	})
}

// HasEatinghistorys applies the HasEdge predicate on the "eatinghistorys" edge.
func HasEatinghistorys() predicate.Taste {
	return predicate.Taste(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(EatinghistorysTable, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, EatinghistorysTable, EatinghistorysColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasEatinghistorysWith applies the HasEdge predicate on the "eatinghistorys" edge with a given conditions (other predicates).
func HasEatinghistorysWith(preds ...predicate.Eatinghistory) predicate.Taste {
	return predicate.Taste(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(EatinghistorysInverseTable, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, EatinghistorysTable, EatinghistorysColumn),
		)
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups list of predicates with the AND operator between them.
func And(predicates ...predicate.Taste) predicate.Taste {
	return predicate.Taste(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for _, p := range predicates {
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Or groups list of predicates with the OR operator between them.
func Or(predicates ...predicate.Taste) predicate.Taste {
	return predicate.Taste(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for i, p := range predicates {
			if i > 0 {
				s1.Or()
			}
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Taste) predicate.Taste {
	return predicate.Taste(func(s *sql.Selector) {
		p(s.Not())
	})
}
