// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"

	"github.com/Teeth/app/ent/eatinghistory"
	"github.com/Teeth/app/ent/foodmenu"
	"github.com/Teeth/app/ent/predicate"
	"github.com/Teeth/app/ent/user"
	"github.com/facebookincubator/ent/dialect/sql"
	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
	"github.com/facebookincubator/ent/schema/field"
)

// FoodmenuUpdate is the builder for updating Foodmenu entities.
type FoodmenuUpdate struct {
	config
	hooks      []Hook
	mutation   *FoodmenuMutation
	predicates []predicate.Foodmenu
}

// Where adds a new predicate for the builder.
func (fu *FoodmenuUpdate) Where(ps ...predicate.Foodmenu) *FoodmenuUpdate {
	fu.predicates = append(fu.predicates, ps...)
	return fu
}

// SetName sets the name field.
func (fu *FoodmenuUpdate) SetName(s string) *FoodmenuUpdate {
	fu.mutation.SetName(s)
	return fu
}

// SetMenuing sets the menuing field.
func (fu *FoodmenuUpdate) SetMenuing(s string) *FoodmenuUpdate {
	fu.mutation.SetMenuing(s)
	return fu
}

// SetAddedtime sets the addedtime field.
func (fu *FoodmenuUpdate) SetAddedtime(s string) *FoodmenuUpdate {
	fu.mutation.SetAddedtime(s)
	return fu
}

// SetGroupid sets the groupid field.
func (fu *FoodmenuUpdate) SetGroupid(i int) *FoodmenuUpdate {
	fu.mutation.ResetGroupid()
	fu.mutation.SetGroupid(i)
	return fu
}

// AddGroupid adds i to groupid.
func (fu *FoodmenuUpdate) AddGroupid(i int) *FoodmenuUpdate {
	fu.mutation.AddGroupid(i)
	return fu
}

// SetTypeid sets the typeid field.
func (fu *FoodmenuUpdate) SetTypeid(i int) *FoodmenuUpdate {
	fu.mutation.ResetTypeid()
	fu.mutation.SetTypeid(i)
	return fu
}

// AddTypeid adds i to typeid.
func (fu *FoodmenuUpdate) AddTypeid(i int) *FoodmenuUpdate {
	fu.mutation.AddTypeid(i)
	return fu
}

// SetCalories sets the calories field.
func (fu *FoodmenuUpdate) SetCalories(i int) *FoodmenuUpdate {
	fu.mutation.ResetCalories()
	fu.mutation.SetCalories(i)
	return fu
}

// AddCalories adds i to calories.
func (fu *FoodmenuUpdate) AddCalories(i int) *FoodmenuUpdate {
	fu.mutation.AddCalories(i)
	return fu
}

// SetOwnerID sets the owner edge to User by id.
func (fu *FoodmenuUpdate) SetOwnerID(id int) *FoodmenuUpdate {
	fu.mutation.SetOwnerID(id)
	return fu
}

// SetNillableOwnerID sets the owner edge to User by id if the given value is not nil.
func (fu *FoodmenuUpdate) SetNillableOwnerID(id *int) *FoodmenuUpdate {
	if id != nil {
		fu = fu.SetOwnerID(*id)
	}
	return fu
}

// SetOwner sets the owner edge to User.
func (fu *FoodmenuUpdate) SetOwner(u *User) *FoodmenuUpdate {
	return fu.SetOwnerID(u.ID)
}

// AddEatinghistoryIDs adds the eatinghistorys edge to Eatinghistory by ids.
func (fu *FoodmenuUpdate) AddEatinghistoryIDs(ids ...int) *FoodmenuUpdate {
	fu.mutation.AddEatinghistoryIDs(ids...)
	return fu
}

// AddEatinghistorys adds the eatinghistorys edges to Eatinghistory.
func (fu *FoodmenuUpdate) AddEatinghistorys(e ...*Eatinghistory) *FoodmenuUpdate {
	ids := make([]int, len(e))
	for i := range e {
		ids[i] = e[i].ID
	}
	return fu.AddEatinghistoryIDs(ids...)
}

// Mutation returns the FoodmenuMutation object of the builder.
func (fu *FoodmenuUpdate) Mutation() *FoodmenuMutation {
	return fu.mutation
}

// ClearOwner clears the owner edge to User.
func (fu *FoodmenuUpdate) ClearOwner() *FoodmenuUpdate {
	fu.mutation.ClearOwner()
	return fu
}

// RemoveEatinghistoryIDs removes the eatinghistorys edge to Eatinghistory by ids.
func (fu *FoodmenuUpdate) RemoveEatinghistoryIDs(ids ...int) *FoodmenuUpdate {
	fu.mutation.RemoveEatinghistoryIDs(ids...)
	return fu
}

// RemoveEatinghistorys removes eatinghistorys edges to Eatinghistory.
func (fu *FoodmenuUpdate) RemoveEatinghistorys(e ...*Eatinghistory) *FoodmenuUpdate {
	ids := make([]int, len(e))
	for i := range e {
		ids[i] = e[i].ID
	}
	return fu.RemoveEatinghistoryIDs(ids...)
}

// Save executes the query and returns the number of rows/vertices matched by this operation.
func (fu *FoodmenuUpdate) Save(ctx context.Context) (int, error) {
	if v, ok := fu.mutation.Name(); ok {
		if err := foodmenu.NameValidator(v); err != nil {
			return 0, &ValidationError{Name: "name", err: fmt.Errorf("ent: validator failed for field \"name\": %w", err)}
		}
	}
	if v, ok := fu.mutation.Menuing(); ok {
		if err := foodmenu.MenuingValidator(v); err != nil {
			return 0, &ValidationError{Name: "menuing", err: fmt.Errorf("ent: validator failed for field \"menuing\": %w", err)}
		}
	}
	if v, ok := fu.mutation.Addedtime(); ok {
		if err := foodmenu.AddedtimeValidator(v); err != nil {
			return 0, &ValidationError{Name: "addedtime", err: fmt.Errorf("ent: validator failed for field \"addedtime\": %w", err)}
		}
	}
	if v, ok := fu.mutation.Groupid(); ok {
		if err := foodmenu.GroupidValidator(v); err != nil {
			return 0, &ValidationError{Name: "groupid", err: fmt.Errorf("ent: validator failed for field \"groupid\": %w", err)}
		}
	}
	if v, ok := fu.mutation.Typeid(); ok {
		if err := foodmenu.TypeidValidator(v); err != nil {
			return 0, &ValidationError{Name: "typeid", err: fmt.Errorf("ent: validator failed for field \"typeid\": %w", err)}
		}
	}
	if v, ok := fu.mutation.Calories(); ok {
		if err := foodmenu.CaloriesValidator(v); err != nil {
			return 0, &ValidationError{Name: "calories", err: fmt.Errorf("ent: validator failed for field \"calories\": %w", err)}
		}
	}

	var (
		err      error
		affected int
	)
	if len(fu.hooks) == 0 {
		affected, err = fu.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*FoodmenuMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			fu.mutation = mutation
			affected, err = fu.sqlSave(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(fu.hooks) - 1; i >= 0; i-- {
			mut = fu.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, fu.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// SaveX is like Save, but panics if an error occurs.
func (fu *FoodmenuUpdate) SaveX(ctx context.Context) int {
	affected, err := fu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (fu *FoodmenuUpdate) Exec(ctx context.Context) error {
	_, err := fu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (fu *FoodmenuUpdate) ExecX(ctx context.Context) {
	if err := fu.Exec(ctx); err != nil {
		panic(err)
	}
}

func (fu *FoodmenuUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   foodmenu.Table,
			Columns: foodmenu.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: foodmenu.FieldID,
			},
		},
	}
	if ps := fu.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := fu.mutation.Name(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: foodmenu.FieldName,
		})
	}
	if value, ok := fu.mutation.Menuing(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: foodmenu.FieldMenuing,
		})
	}
	if value, ok := fu.mutation.Addedtime(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: foodmenu.FieldAddedtime,
		})
	}
	if value, ok := fu.mutation.Groupid(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: foodmenu.FieldGroupid,
		})
	}
	if value, ok := fu.mutation.AddedGroupid(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: foodmenu.FieldGroupid,
		})
	}
	if value, ok := fu.mutation.Typeid(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: foodmenu.FieldTypeid,
		})
	}
	if value, ok := fu.mutation.AddedTypeid(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: foodmenu.FieldTypeid,
		})
	}
	if value, ok := fu.mutation.Calories(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: foodmenu.FieldCalories,
		})
	}
	if value, ok := fu.mutation.AddedCalories(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: foodmenu.FieldCalories,
		})
	}
	if fu.mutation.OwnerCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   foodmenu.OwnerTable,
			Columns: []string{foodmenu.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: user.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := fu.mutation.OwnerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   foodmenu.OwnerTable,
			Columns: []string{foodmenu.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: user.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if nodes := fu.mutation.RemovedEatinghistorysIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   foodmenu.EatinghistorysTable,
			Columns: []string{foodmenu.EatinghistorysColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: eatinghistory.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := fu.mutation.EatinghistorysIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   foodmenu.EatinghistorysTable,
			Columns: []string{foodmenu.EatinghistorysColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: eatinghistory.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, fu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{foodmenu.Label}
		} else if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return 0, err
	}
	return n, nil
}

// FoodmenuUpdateOne is the builder for updating a single Foodmenu entity.
type FoodmenuUpdateOne struct {
	config
	hooks    []Hook
	mutation *FoodmenuMutation
}

// SetName sets the name field.
func (fuo *FoodmenuUpdateOne) SetName(s string) *FoodmenuUpdateOne {
	fuo.mutation.SetName(s)
	return fuo
}

// SetMenuing sets the menuing field.
func (fuo *FoodmenuUpdateOne) SetMenuing(s string) *FoodmenuUpdateOne {
	fuo.mutation.SetMenuing(s)
	return fuo
}

// SetAddedtime sets the addedtime field.
func (fuo *FoodmenuUpdateOne) SetAddedtime(s string) *FoodmenuUpdateOne {
	fuo.mutation.SetAddedtime(s)
	return fuo
}

// SetGroupid sets the groupid field.
func (fuo *FoodmenuUpdateOne) SetGroupid(i int) *FoodmenuUpdateOne {
	fuo.mutation.ResetGroupid()
	fuo.mutation.SetGroupid(i)
	return fuo
}

// AddGroupid adds i to groupid.
func (fuo *FoodmenuUpdateOne) AddGroupid(i int) *FoodmenuUpdateOne {
	fuo.mutation.AddGroupid(i)
	return fuo
}

// SetTypeid sets the typeid field.
func (fuo *FoodmenuUpdateOne) SetTypeid(i int) *FoodmenuUpdateOne {
	fuo.mutation.ResetTypeid()
	fuo.mutation.SetTypeid(i)
	return fuo
}

// AddTypeid adds i to typeid.
func (fuo *FoodmenuUpdateOne) AddTypeid(i int) *FoodmenuUpdateOne {
	fuo.mutation.AddTypeid(i)
	return fuo
}

// SetCalories sets the calories field.
func (fuo *FoodmenuUpdateOne) SetCalories(i int) *FoodmenuUpdateOne {
	fuo.mutation.ResetCalories()
	fuo.mutation.SetCalories(i)
	return fuo
}

// AddCalories adds i to calories.
func (fuo *FoodmenuUpdateOne) AddCalories(i int) *FoodmenuUpdateOne {
	fuo.mutation.AddCalories(i)
	return fuo
}

// SetOwnerID sets the owner edge to User by id.
func (fuo *FoodmenuUpdateOne) SetOwnerID(id int) *FoodmenuUpdateOne {
	fuo.mutation.SetOwnerID(id)
	return fuo
}

// SetNillableOwnerID sets the owner edge to User by id if the given value is not nil.
func (fuo *FoodmenuUpdateOne) SetNillableOwnerID(id *int) *FoodmenuUpdateOne {
	if id != nil {
		fuo = fuo.SetOwnerID(*id)
	}
	return fuo
}

// SetOwner sets the owner edge to User.
func (fuo *FoodmenuUpdateOne) SetOwner(u *User) *FoodmenuUpdateOne {
	return fuo.SetOwnerID(u.ID)
}

// AddEatinghistoryIDs adds the eatinghistorys edge to Eatinghistory by ids.
func (fuo *FoodmenuUpdateOne) AddEatinghistoryIDs(ids ...int) *FoodmenuUpdateOne {
	fuo.mutation.AddEatinghistoryIDs(ids...)
	return fuo
}

// AddEatinghistorys adds the eatinghistorys edges to Eatinghistory.
func (fuo *FoodmenuUpdateOne) AddEatinghistorys(e ...*Eatinghistory) *FoodmenuUpdateOne {
	ids := make([]int, len(e))
	for i := range e {
		ids[i] = e[i].ID
	}
	return fuo.AddEatinghistoryIDs(ids...)
}

// Mutation returns the FoodmenuMutation object of the builder.
func (fuo *FoodmenuUpdateOne) Mutation() *FoodmenuMutation {
	return fuo.mutation
}

// ClearOwner clears the owner edge to User.
func (fuo *FoodmenuUpdateOne) ClearOwner() *FoodmenuUpdateOne {
	fuo.mutation.ClearOwner()
	return fuo
}

// RemoveEatinghistoryIDs removes the eatinghistorys edge to Eatinghistory by ids.
func (fuo *FoodmenuUpdateOne) RemoveEatinghistoryIDs(ids ...int) *FoodmenuUpdateOne {
	fuo.mutation.RemoveEatinghistoryIDs(ids...)
	return fuo
}

// RemoveEatinghistorys removes eatinghistorys edges to Eatinghistory.
func (fuo *FoodmenuUpdateOne) RemoveEatinghistorys(e ...*Eatinghistory) *FoodmenuUpdateOne {
	ids := make([]int, len(e))
	for i := range e {
		ids[i] = e[i].ID
	}
	return fuo.RemoveEatinghistoryIDs(ids...)
}

// Save executes the query and returns the updated entity.
func (fuo *FoodmenuUpdateOne) Save(ctx context.Context) (*Foodmenu, error) {
	if v, ok := fuo.mutation.Name(); ok {
		if err := foodmenu.NameValidator(v); err != nil {
			return nil, &ValidationError{Name: "name", err: fmt.Errorf("ent: validator failed for field \"name\": %w", err)}
		}
	}
	if v, ok := fuo.mutation.Menuing(); ok {
		if err := foodmenu.MenuingValidator(v); err != nil {
			return nil, &ValidationError{Name: "menuing", err: fmt.Errorf("ent: validator failed for field \"menuing\": %w", err)}
		}
	}
	if v, ok := fuo.mutation.Addedtime(); ok {
		if err := foodmenu.AddedtimeValidator(v); err != nil {
			return nil, &ValidationError{Name: "addedtime", err: fmt.Errorf("ent: validator failed for field \"addedtime\": %w", err)}
		}
	}
	if v, ok := fuo.mutation.Groupid(); ok {
		if err := foodmenu.GroupidValidator(v); err != nil {
			return nil, &ValidationError{Name: "groupid", err: fmt.Errorf("ent: validator failed for field \"groupid\": %w", err)}
		}
	}
	if v, ok := fuo.mutation.Typeid(); ok {
		if err := foodmenu.TypeidValidator(v); err != nil {
			return nil, &ValidationError{Name: "typeid", err: fmt.Errorf("ent: validator failed for field \"typeid\": %w", err)}
		}
	}
	if v, ok := fuo.mutation.Calories(); ok {
		if err := foodmenu.CaloriesValidator(v); err != nil {
			return nil, &ValidationError{Name: "calories", err: fmt.Errorf("ent: validator failed for field \"calories\": %w", err)}
		}
	}

	var (
		err  error
		node *Foodmenu
	)
	if len(fuo.hooks) == 0 {
		node, err = fuo.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*FoodmenuMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			fuo.mutation = mutation
			node, err = fuo.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(fuo.hooks) - 1; i >= 0; i-- {
			mut = fuo.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, fuo.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX is like Save, but panics if an error occurs.
func (fuo *FoodmenuUpdateOne) SaveX(ctx context.Context) *Foodmenu {
	f, err := fuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return f
}

// Exec executes the query on the entity.
func (fuo *FoodmenuUpdateOne) Exec(ctx context.Context) error {
	_, err := fuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (fuo *FoodmenuUpdateOne) ExecX(ctx context.Context) {
	if err := fuo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (fuo *FoodmenuUpdateOne) sqlSave(ctx context.Context) (f *Foodmenu, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   foodmenu.Table,
			Columns: foodmenu.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: foodmenu.FieldID,
			},
		},
	}
	id, ok := fuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "ID", err: fmt.Errorf("missing Foodmenu.ID for update")}
	}
	_spec.Node.ID.Value = id
	if value, ok := fuo.mutation.Name(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: foodmenu.FieldName,
		})
	}
	if value, ok := fuo.mutation.Menuing(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: foodmenu.FieldMenuing,
		})
	}
	if value, ok := fuo.mutation.Addedtime(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: foodmenu.FieldAddedtime,
		})
	}
	if value, ok := fuo.mutation.Groupid(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: foodmenu.FieldGroupid,
		})
	}
	if value, ok := fuo.mutation.AddedGroupid(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: foodmenu.FieldGroupid,
		})
	}
	if value, ok := fuo.mutation.Typeid(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: foodmenu.FieldTypeid,
		})
	}
	if value, ok := fuo.mutation.AddedTypeid(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: foodmenu.FieldTypeid,
		})
	}
	if value, ok := fuo.mutation.Calories(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: foodmenu.FieldCalories,
		})
	}
	if value, ok := fuo.mutation.AddedCalories(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: foodmenu.FieldCalories,
		})
	}
	if fuo.mutation.OwnerCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   foodmenu.OwnerTable,
			Columns: []string{foodmenu.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: user.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := fuo.mutation.OwnerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   foodmenu.OwnerTable,
			Columns: []string{foodmenu.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: user.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if nodes := fuo.mutation.RemovedEatinghistorysIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   foodmenu.EatinghistorysTable,
			Columns: []string{foodmenu.EatinghistorysColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: eatinghistory.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := fuo.mutation.EatinghistorysIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   foodmenu.EatinghistorysTable,
			Columns: []string{foodmenu.EatinghistorysColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: eatinghistory.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	f = &Foodmenu{config: fuo.config}
	_spec.Assign = f.assignValues
	_spec.ScanValues = f.scanValues()
	if err = sqlgraph.UpdateNode(ctx, fuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{foodmenu.Label}
		} else if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return nil, err
	}
	return f, nil
}
